### ISSUE TITLE
Local Installation

### ISSUE THREAD

**Issue by Nash0990** [Kyoko-wtnb/FUMA-webapp#1]
Hi, 

I have been working on trying to replicate the whole FUMA-webapp on my local PC and am able to get the front end of the app running and I am facing a few issues.

1. By default, every run creates a folder in the root "/jobs/1", after going through the multiple config files, I identified that in the sessions.php inside the config folder we can change the path variable from "/" to any other folder, with write permissions but it seems it is still trying to save it in the root "/jobs/" folder. The workaround for was to run the server as root.

2. Once I got it up and running as root, when I tried to run an example file, the process throws an error regarding the config file (/FUMA-webapp/storage/script/app.config) that needs to have the pointers to where all the different tools and databases need to be stored. Could you please mention share the versions of tools and databases used in the online webapp, so as that the results would be consistent.

**Comment by Kyoko-wtnb** [comment]
Hi,

There is actually a variable need to be defined in .env file.
For the snp2gene jobs, you need to define
APP_JOBDIR=<here is your desired path before /jobs>

All the software and data used in FUMA is listed at http://fuma.ctglab.nl/links
But most of the files need to be pre-processed to have specific format.
Actually current repository is not really meant for replicate entire FUMA but just to share source code so users can see what is actually going on behind.
I meant to write documentations for all details what files need to be in which format and where to specify paths.
Also, I'm planning to create separate repository only for the main process of the FUMA (without PHP frame work). That will be much easier to run FUMA locally.
I cannot promise but planning to do so by this summer.
I'm sorry for all your efforts and inconvenience but might be difficult to replicate FUMA right now.

Best,
Kyoko
