### ISSUE TITLE
FUMA server currently down

### ISSUE THREAD

**Issue by dgarrimar** [Kyoko-wtnb/FUMA-webapp#10]
It seems [https://fuma.ctglab.nl](https://fuma.ctglab.nl/) is currently not reachable.

**Comment by wilcas** [comment]
As of today it seems the server is once again reachable

**Comment by dgarrimar** [comment]
Yep! thanks for letting know

**Comment by medack** [comment]
I have been unable to reach the server for some time. Could it be down again?
