### ISSUE TITLE
Run in Docker container

### ISSUE THREAD

**Issue by faridhb** [Kyoko-wtnb/FUMA-webapp#2]
Hi,

I would like to run the FUMA-webapp in a docker container. 
Do you have any tipps to achieve this ? 
Is there any detailed documentation about the web-app and its files?

Best regards,

Farid

**Comment by Kyoko-wtnb** [comment]
Hi Farid,

I am working on to create a stand-alone version of FUMA tight now, that would be much easier to run by your self.
I'm also preparing detailed documentation to reproduce FUMA on your local computer but can also create Docker as well.

Best,
Kyoko

**Comment by beeemT** [comment]
@Kyoko-wtnb I am currently working on a pipeline for GWAS. Part of this pipeline would be FUMA.
I would be interested in creating a docker container for FUMA as my thesis. Could we maybe collaborate ? Please contact me at benedikt.maximilian.thoma@gmail.com.

Best Regards,
Benedikt

**Comment by Kyoko-wtnb** [comment]
Hi Benedikt,

Thank you for your message, I'll follow you up by email.

Best,
Kyoko
